spring:
  application:
    name: sitegirabar

  # Perfil padr√£o (caso nenhum seja informado)
  profiles:
    active: local

# üîπ Configura√ß√£o base (comuns a todos os ambientes)
server:
  port: ${PORT:8080}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---

# üß† Perfil LOCAL (para rodar com seu Docker ou MySQL instalado)
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3307/db_sitegirabar?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: appuser
    password: apppass
    driver-class-name: com.mysql.cj.jdbc.Driver

---

# ‚òÅÔ∏è Perfil PROD (para o Railway)
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${MYSQLHOST:mysql.railway.internal}:${MYSQLPORT:3306}/${MYSQLDATABASE:railway}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:VSIOPyiUuogsNPSWgWjCksjAZAQYywyh}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

